# Netlify Settings
[build]
  # Build command (not needed for static site)
  command = ""
  # Publish directory - the folder containing your site files
  publish = "."

# Redirect rules for SPA routing
[[redirects]]
  # Handle 404s by serving index.html (for single page apps)
  from = "/*"
  to = "/index.html"
  status = 200
  # Exclude actual files from redirect
  conditions = {path = "!**.html", path = "!**.css", path = "!**.js", path = "!**.png", path = "!**.jpg", path = "!**.ico"}

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Performance headers
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"